### ISSUE TITLE
直播源问题反馈

### ISSUE THREAD

**Issue by huangsuming** [huangsuming/iptv#1]

**Comment by yalicez** [comment]
你好，文件名tvlist.txt是否应为tvlist.m3u，有的壳读不出来tvlist.txt

**Comment by huangsuming** [comment]
#你好，文件名tvlist.txt
可以自己保存后改下，或者做个定时任务克隆到自己的项目上改后缀。

**Comment by huangsuming** [comment]
# 你好，文件名tvlist.txt是否应为tvlist.m3u
可以自己保存后改下，或者做个定时任务克隆到自己的项目上改后缀。

**Comment by huangsuming** [comment]
#2063074983

**Comment by huangsuming** [comment]
> 你好，文件名tvlist.txt是否应为tvlist.m3u，有的壳读不出来tvlist.txt

可以自己保存后改下，或者做个定时任务克隆到自己的项目上改后缀。
